
all: play_random play_greedy play_gui
	raco make game.rhm slide.rhm play_random.rhm play_greedy.rhm play_gui.rhm

play_random:
	raco exe --launcher play_random.rhm

play_greedy:
	raco exe --launcher play_greedy.rhm

play_gui:
	raco exe --launcher play_gui.rhm 
