#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/Users/mflatt/plt/racket/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-t' '/Users/mflatt/repo/oflatt/economancy/player/play_random.rhm' '-U' '--'  ${1+"$@"}
