name: Build game


on: [push]



jobs:
  build-game:
    name: "Build game"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.9
        with:
          version: "8.10"
      - uses: actions/checkout@master
      - uses: coactions/setup-xvfb@v1
      - run: racket cardgame.rkt