name: Build game


on: [push]



jobs:
  build-game:
    name: "Build game"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.9
        with:
          version: "8.10"
      - name: Install Font
        run: |
          wget -O PT_Sans.zip https://fonts.google.com/download?family=PT%20Sans
          unzip -d pt_sans/ PT_Sans.zip
          mv pt_sans /usr/share/fonts/
          fc-cache -fv
      - uses: actions/checkout@master
      - name: "Run makefile"
        uses: coactions/setup-xvfb@v1
        with:
          run: make

      - uses: actions/upload-artifact@v4
        with:
          name: cards-artifact
          path: cards
