name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Make game
        uses: coactions/setup-xvfb@v1
        with:
          run: make
      - uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: docs